src/repository.ts, test/3.repo.open.ts
Add support for `Repository.open` opening a sub-directory and still finding the repo
Fixes #4
=> :bug: snow not detected from subdirectory

bin/snow
Stop using hard coded /usr/local/bin/node.
Prevent crashes when node is at other locations, like /usr/bin/node.
It wouldn't run for me on my Linux machine where node is located at /usr/bin/node
Now, wherever it finds node in PATH first it will use that. I'm not totally sure if there is some specific convention for when a user wants to supply their own version of node, but this will at least fix a lot of cases on Linux.
Please delete options that are not relevant.
=> :penguin: Add support for different node executable locations

main.ts
In this issue `head.getName()` was used instead of checking if the head is detached.
=> :bug: Incorrect HEAD value when json-pretty is used (Closes #39)

src/odb.ts
[ensureDir](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md) is used to create a potentially missing directory
=> Checkout to an older commit does not restore directories (Closes #41)

.vscode/launch.json
The VScode run configurations are now relabeled.
- **Launch CLI (main.ts)** 
_Executes bin/_
- **Launch Test (test/*)**
_Executes test/_
- **Launch Benchmark**
Executes benchmarks/snowfs-vs-git.ts
=> 🐛  Update launch json

README.md
A simple clarification in the readme  to express our interest in a C++ backport. It would also open the doors for other environments (e.g. a native Python module).
=> :memo: clarify C++ backport

main.ts, src/commit.ts, src/odb.ts, src/repository.ts, test/4.repo.commit.ts, test/9.cli.ts
The ability to add **tags** to commits makes it easier to semantically filter for specific changes within a repository.
Tags can be added via the commandline when committing, e.g.:
`cwd>snow commit -m "Move Player Spawn Point to avoid Obstacle" --tags=mountain-level,layout-three,pirates`
Tags can be read via the json file received from the log command.
```
{
"hash": "c586098a16d877e0caf649239800fc0b1f6632f5b3113a5b484b05caf11504fd",
"message": "Move Player Spawn Point to avoid Obstacle",
"date": 1614300177.598,
"tags": [
"mountain-level",
"layout-three",
"pirates"
],
"userData": {}
}
```
Closes #37
=> :star: Add support for tags to commits

main.ts, test/9.cli.ts
Add a `parseOptions` function, that can optionally extract parsed arguments from `stdin` or a file path.
`parseOptions` is a helper function for additional parsing options. Some CLI commands support passing information through stdin or a text-file (e.g. --user-data for commits). If the passed options object contains 'input', the options can be loaded from a stdin, otherwise the value is treated as a file path. The content is extracted from the source and applied on top of the 'opts' object.
=> :star: add support for --input=stdin/filepath (Fixes: #55)

main.ts, src/odb.ts, src/reference.ts, src/repository.ts, test/9.cli.ts
Add the option to write, store and read additional data for refs. This will allow flexible customization for end users.
When creating a new branch, user data can be added via the command 
`snow checkout -b branch-name --input=stdin`
and subsequently writing
`--user-data:{"color" : "#FF3245"}`
to the std input. This will resilt in a new branch with the following layout.
```
{
"hash" : "96ad22c7b26f3042bc2fc7437dc704a7e7c2b53553cbf8d97f90a0ea498c14c2",
"userData" : 
{
"color" : "#FF3245"
}
}
```
(Closes #35)
=> :star: Add support for user data in refs

src/common.ts, src/index.ts, src/io_context.ts, src/repository.ts
Whenever SnowFS is embedded in another environment (e.g. Snowtrack), the files for `trash` or `recycle-bin.exe` might be located at a different location. To find them `IoContext.setTrashExecPath` should be called once on startup with a path to the given executable.
=> :bug: recycle-bin.exe / trash not found (Closes: 76)

src/log.ts, src/repository.ts, test/2.repo.init.ts
This PR introduces a simple log system. Logs are written to `./snow/logs`.
```
1615665880182 -0500 $> init: initialized at C:\Users\sebastian\Desktop\foo2
1615665880209 -0500 $> commit: Created Project
1615666315903 -0500 $> reference: creating branch-xyz at e1df41702d8f65342c1cb078478929e6d70008b446c812949225aa707d869a5d
```
=> :star: Add logging support

src/odb.ts
If a branch is restored, the subdirectories are now restored as well.
```
snow init foo
cd foo
mkdir subdir
echo "Test" > subdir/test.txt
snow add .
snow commit -m "add test.txt"
snow rm subdir
snow commit -m "delete test.txt"
snow log
snow checkout <HASH-OF-COMMIT_ADD_TEST.TXT>
```
=> :bug: ensure dst directory exists (Closes: #88)

bin/snow, bin/snow.bat
Use `TS_NODE_TRANSPILE_ONLY` to speedup compilation speed as recommended [here](https://github.com/TypeStrong/ts-node/discussions/1276#discussioncomment-489839).
The type-checking is done by `npm run build` before.
=> :bug: add TS_NODE_TRANSPILE_ONLY to speedup compilation

src/fs-safe.ts, src/index.ts, src/io_context.ts, src/odb.ts, test/1.sys.test.ts
Introduce `fss.writeSafeFile` to write files to disk atomically, but writing the file first to disk and then doing a rename (which is atomically).
=> :star: introduce fss.writeSafeFile

src/repository.ts, test/4.repo.commit.ts
Add support for commit lookup `branch~n`, like `Main~1`. This is an extension of `HEAD~1` where from now on, also the branch can be used.
=> Add support for branch~n

src/repository.ts
Adding repository init options to set a default branch name or default message for the first commit
=> :star: add repository init options

main.ts
As described in #152, `snow log` literally returned 'HEAD' instead of the commit-hash
=> :bug: head printed 'HEAD' instead of commit hash (Closes: #152)

package.json, src/io.ts, src/repository.ts
Introduce [winattr](https://github.com/stevenvachon/winattr) to set a file/dir attribute to hide a given item. The module is only loaded on Windows, and skipped on Linux/Darwin.
=> :bug: introduce winattr to set hidden attribute on Win (Closes: 156)

src/common.ts, src/io.ts, src/odb.ts, src/repository.ts, src/treedir.ts
This change keeps the extensions for stored files in the object database. More information are available in #158. It also keeps the file extensions alive when files are moved to the trash.
=> :star: Keep file extensions for files in odb (Closes: 158)

src/odb.ts
This bugfix catches specific error messages thrown by `fse.move`, despite the `overwrite: false` argument.
=> :bug: prevent move from failing on Windows (Closes: 163)

src/ignore.ts, src/repository.ts
This change introduces a speedup for `snow status` and `snow add`. Both rely on the ignore handling, which was slow due to the call of `ignore.ignored(file, this.patterns)` for each single file. The module [micromatch](https://github.com/micromatch/micromatch) which is used under the hood, evaluated the regex for each file. Passing over a list of all files in a single shot results in the speed improvements as demonstrated below - same repo as from the initial bug report (> 40000 files):
```
$ ls -lsa | wc -l
40003
$ time /c/Users/sebastian/Documents/git/SnowFS/dist/out-tsc/snow.exe status > /c/Users/sebastian/Desktop/output.txt
real    0m2.142s
user    0m0.015s
sys     0m0.000s
$ time /c/Users/sebastian/Documents/git/SnowFS/dist/out-tsc/snow.exe add .
real    0m31.213s
user    0m0.015s …
```
=> :racehorse: speedup ignore handling

main.ts, src/common.ts, src/io.ts, src/io_context.ts, src/odb.ts, src/repository.ts, src/treedir.ts, test/1.sys.test.ts
This PR introduces several optimizations and changes
1) Stats added to `TreeDir`, `TreeFile`, `StatusEntry` and `DirItem`. When a `TreeEntry` is restored, the `mtime` is set to ensure they match exactly the `mtime` from the file in the commit.
2) `checkout` and `status` can now choose between 3 detection modes
- only size and mktime
- size and mtime for files > 20MB otherwise filehash
- size and hash for all files
3) On `checkout`, the file is now tested for writability, to return a proper error message, if a file permission would prevent the checkout from succeeding
=> Add stats to (Tree/Status)Entry/DirItem, add access test + restore mtime

benchmark/snowfs-vs-git.ts, main.ts, src/commit.ts, src/io_context.ts, src/odb.ts, src/reference.ts, src/repository.ts, src/treedir.ts, test/1.sys.test.ts, test/6.ignore.ts, test/9.cli.ts, test/helper.ts
Unspecific cleanup of changes, and `putToTrash` now prints the relative path to make potential error messages shorter
=> fix warnings and cleanup error messages

src/common.ts, src/index.ts, src/io.ts, src/io_context.ts, src/odb.ts, src/repository.ts, src/treedir.ts
This bugfix uses the original `fs` module inside an Electron app. it is recommended, to use the `./io` module from now on whenever possible to ensure that either `fs` or `original-fs` is used.
=> :bug: speedup snowfs inside electron app

src/ignore.ts
Ignore Corel Draw Backup files `Backup_of_*`
=> Ignore Corel Draw Backup files (Closes: #180)

src/io.ts, test/1.sys.test.ts
This PR prevents `osWalk` from failing if an item in the directory fails on `stat` which might be the case for a deleted item while iterating.
This PR also introduces two intensive unit-tests that test...
1. ... deleting while iterating.
2. ... moving an entire directory out and back the directory while osWalk is running
=> Prevent osWalk from failing (Closes: #192)

src/io_context.ts, src/repository.ts
This PR speeds up the moving files to the recycle-bin/trash. The corresponding executables (recycle-bin.exe/trash) accept multiple files as input. Instead of calling the process for each file manually, they are now bundled into chunks.
Additionally, a PromisePool is used to prevent a process flood.
=> Speeding up moving files to the recycle bin

.github/workflows/workflow.yml, README.md, package.json, src/diff.ts, test/7.repo.diff.ts, test/8.ignore.ts, test/9.iocontext.ts
This PR introduces a new class called `Diff` to compare two commits.
=> :star: Introduce a diff class to compare two commits

.vscode/settings.json, tsconfig.json
VScode might accidentally use a wrong TypeScript version.
Adding a `settings.json` file and setting the version in `tsconfig.json`.
=> set typescript version to 4.3.4

src/repository.ts, test/2.repo.init.ts, test/3.repo.open.ts, test/helper.ts
Fixes and closes #232 by adding a check to ensure `Repository.init` never replaces a workdir or commondir
=> :bug: Bugfix/issue 232

src/repository.ts
`Repository.init` checked for the existence of workdir, instead it must check for `workdir/.snow` to complain about the existence.
=> only complain if .snow exists

src/io_context.ts, test/1.sys.test.ts, test/3.repo.open.ts
On MacOS and Linux we determine if files are opened in read, write or read+write mode before they are copied to the index. Some applications (like InDesign) open their active documents in read+write mode. Before this fix, we threw an error and reported that the file is being written, which might not be the case overall.
This PR distinguishes if a file is in read, write or read+write mode. Every file that is opened in write+read mode is now tested if it is really being written by falling back to the same approach we use on Windows.
=> use alternative read check if file is opened in read+write mode

.github/workflows/workflow.yml
Minor changes to the GH workflow. Bump of workflow actions and remove unnecessary `.zip` suffix.
=> Bump workflow actions

.github/workflows/workflow.yml
Use `npm ci` instead of `npm install` for the build pipeline.
See https://docs.npmjs.com/cli/v8/commands/npm-ci
> This command is similar to [npm install](https://docs.npmjs.com/cli/v8/commands/npm-install), except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation where you want to make sure you're doing a clean install of your dependencies.
=> Use npm run ci-all to build SnowFS

README.md
The download button in the `README.md` still used the Alpha label. Update to `beta` for https://github.com/snowtrack/snowfs/releases/tag/v0.9.2
=> :broom: Rename 'alpha' to 'beta' in download button

benchmark/snowfs-vs-git.ts, package.json
This PR fixes the benchmark test for GitHub runner. The test size is also reduced to 1GB for Windows since they run easily out of memory.
=> Fix benchmark tests
