snowtrack/snowfs

main.ts
package-lock.json
package.json
src/index.ts
src/odb.ts
src/repository.ts
test/4.repo.commit.ts
test/onlysnowtrack.zip

Variety of fixes and features for CLI

Variety of fixes and features

---

benchmarks/snowfs-vs-git.ts
bin/IMPORTANT.md
bin/snow
bin/snow.bat
main.ts
src/common.ts
src/index.ts
src/odb.ts
src/repository.ts
test/1.sys.test.ts
test/10.benchmark.ts
test/2.repo.init.ts
test/4.repo.commit.ts

Fix https://github.com/Snowtrack/SnowFS/issues/11
Fix https://github.com/Snowtrack/SnowFS/issues/10
Various other non-reported fixes
Add benchmarks

Basic fixes

---

README.md
package-lock.json
package.json
test/9.cli.ts

Add nyc coverage report and add missing benchmark env

nyc coverage report

---

.github/workflows/workflow.yml
README.md
benchmarks/snowfs-vs-git.ts
bin/snow.bat
package-lock.json
package.json
test/10.benchmark.ts
test/9.cli.ts

Fix #7 and add coverage support

Add GitHub Actions and Code Coverage

---

.github/workflows/workflow.yml
benchmarks/snowfs-vs-git.ts
package.json
src/commit.ts
src/common.ts
test/1.sys.test.ts
test/4.repo.commit.ts

:art: update benchmarks, tests, hash functions and workflows

---

package.json
resources/Clone-FileViaBlockClone.ps1
resources/LICENSE-Clone-FileViaBlockClone.txt
src/ignore.ts
src/io_context.ts
test/4.repo.commit.ts
test/8.iocontext.ts

Add support for ReFS #1 and prepare hooks and code for easy integration of other filesystems

Add initial support for ReFS

---

README.md
package.json
resources/Clone-FileViaBlockClone.ps1
resources/LICENSE-Clone-FileViaBlockClone.txt
src/ignore.ts
src/io_context.ts
test/4.repo.commit.ts
test/8.iocontext.ts

Add benchmark values to README

Benchmark readme

---

CONTRIBUTORS.md

change to github repo link as requested

:memo: change to github repo link as requested

---

README.md

:memo: missing file details for benchmark

---

README.md

Some pointed out, that the argument is not valid, and I highly agree. The argument is not sustainable

:memo: remove invalid argument

---

.github/workflows/workflow.yml

Disable the Discord job for now

disable discord job

---

benchmarks/snowfs-vs-git.ts
main.ts
src/commit.ts
src/index.ts
src/odb.ts
src/repository.ts
test/4.repo.commit.ts
test/9.cli.ts

Add the ability to write, store and read additional
arbitrary user data to commits. Add some work on tests.
Fixes #36

:star: Add support for user data in commits

---

src/repository.ts

:memo: fix commit message

---

test/9.cli.ts

Minor fix about process environment variables not passed to the subprocess

:bug: Pass process environment to subprocess

---

main.ts
test/9.cli.ts

If the JSON input for user-data is invalid, we simply let the command fail

If JSON input for user-data is invalid, fail commit (Close: #59)

---

main.ts
test/9.cli.ts

Introduced 4 unittests for `snow rm`
```
snow rm foo.txt
snow rm subdir
snow rm subdir/bar.txt
snow rm file-does-not-exist
```

:star: add snow rm unittests

---

.eslintrc.json
CONTRIBUTORS.md

Fixes the LF / CLRF errors on Windows
Fixes #69

Issue 69 linebreak style

---

README.md

Adding Btrfs (see https://github.com/Snowtrack/SnowFS/discussions/57)

:memo: Update Readme

---

.github/workflows/workflow.yml

[coveralls.io](https://coveralls.io/) requires the parallel option. For more information see https://github.com/coverallsapp/github-action#complete-parallel-job-example

:bug: add coveralls parallel option

---

.vscode/launch.json

Fixes #81 
For more information check out https://github.com/microsoft/vscode/issues/102042#issuecomment-658522299

Fix error message in console when debugging (Closes: #81)

---

benchmarks/snowfs-vs-git.ts
main.ts
src/common.ts
src/index.ts
src/io_context.ts
src/odb.ts
src/repository.ts
src/treedir.ts
test/2.repo.init.ts
test/4.repo.commit.ts
test/9.cli.ts

This PR introduces a multi-staging area with a few additions:
- Index files are now stored in `.snow/indexes`
- Main index file is simply called `index`
- Custom index files are called `index.{hash}`
- Index files are now deleted upon commit
- Introduce `--index` for `snow add/log/commit/rm`
- New indexes can be created through `snow index create`

Introducing multi-staging area

---

src/commit.ts
src/common.ts

Fixed an issue where after passing a multiline commit message, future snow status invocations fail.
Fixes #85

:bug: Escape commit message for json

---

src/log.ts

Ignore errors if a log cannot be written to disk.

Ignore errors if a log cannot be written to disk

---

package.json
src/ignore.ts
test/11.ignore.ts

SnowFS provides the ability to ignore files within the repository when executing snow commands. Ensure desired behaviour of the ignore feature and improve doumentation for edge cases by writing tests.
Fixes # (102)

:white_check_mark: Add tests for snow ignore

---

README.md
benchmark/snowfs-vs-git.ts

👕 Minor cleanups

---

package.json
src/io.ts
src/repository.ts
test/2.repo.init.ts
test/3.repo.open.ts
test/4.repo.commit.ts
test/5.repo.checkout.ts
test/8.iocontext.ts
test/helper.ts

Add additional tests to add/modify and delete files when checkout is called

:star: Add checkout test

---

.vscode/launch.json
src/repository.ts
test/5.repo.checkout.ts

Content of `.snowignore` was ignored during checkout or switch.

Don't ignore snowignore in checkout/switch

---

README.md
main.ts
src/repository.ts

Small minor cleanups and changes

🎨 bring getStatus and checkout closer together

---

src/index.ts
src/odb.ts
src/repository.ts
test/2.repo.init.ts

Introduce a `state` flag in the **commondir**. It contains a random sha256 hash, to indicate if the repository got modified. This file can be polled or checked regularly if needed.

⭐ add dirty flag file

---

src/path.ts

add extname

---

main.ts

Add missing flag due to refactoring (Closes #136)

Update flags for snow add

---

src/io_context.ts

Fix incorrect usage of `spawn` and `on` callbacks

close and error callback must be registered right after spawn (Closes #142)

---

src/repository.ts

:memo: update error message

---

src/io.ts

`osWalk` will not fail anymore if a sub-directory is deleted. I also added a new flag called `NO_RECURSIVE` to iterate through the first level of the directory.
Additionally, `.DS_Store` and `thumbs.db` are now properly ignored, and other hidden files processed accordingly to the passed flags

:bug: Make osWalk not fail if items get deleted (Closes: #154)

---

.github/workflows/workflow.yml

Test the executable during GitHub actions, to ensure it really works. (Closes: #167)

test executable to ensure it doesn't fail on start

---

src/io_context.ts

If a file is copied through the Windows explorer, the full size of the file is already set at the beginning of the copy routine, so the check below didn't detect being written to.
https://github.com/Snowtrack/SnowFS/blob/1803b85d9ca20ea0a908e88627d934a383cddd87/src/io_context.ts#L508
Instead, the `mtime` is continuously updated, which is now part of the check

In not all cases a file copy is detected (Closes: 175)

---

src/io.ts
src/odb.ts
src/path.ts
src/repository.ts

With this PR SnowFS ensures that all items that are deleted or overwritten are moved to the recycle bin if they are not backed up in the ODB, otherwise they are good to be deleted

Move items to trash if they are not backed up in the odb (Closes: #178)

---

src/repository.ts

```
snow init foo
mkdir foo
cd foo
touch foo/bar
snow add .
snow commit -m "Initial commit"
echo "edited file" > foo/bar
snow status
```
Compare the output below with the output from the bugfix.
```
Changes not staged for commit:
use "snow add <rel-path>..." to update what will be committed
foo <--- new
foo/bar
```
**Important: `snow status` might exclude directories in the future but this PR is about the underlying `getStatus` function.

Mark directories as modified if their content changed (Closes: #187)

---

src/io_context.ts

Fix string

---

src/ignore.ts

Update default snowignore

---

test/1.sys.test.ts
test/precalculate_hashes.py

Cherry pick of unit tests from https://github.com/seb-mtl/snowfs/tree/feature/unit-tests to snowtrack/snowfs

Add file hash unit tests

---

src/ignore.ts

Ignore auto safe files created by Adobe After Effects/Premiere Pro

Add AE/AP ignore

---

CONTRIBUTORS.md
README.md

`cd snowfs.git`  -> `cd snowfs`
Fixes #205
Please delete options that are not relevant.

Fix typo in build instructions

---

.github/workflows/workflow.yml
README.md
package-lock.json
package.json
src/io_context.ts
test/10.cli.ts
test/helper.ts

This PR introduces Linux support

Add Linux support

---

.github/workflows/workflow.yml
package-lock.json
package.json
src/io.ts
test/2.repo.init.ts
test/3.repo.open.ts
test/5.repo.commit.ts
test/helper.ts

Bump versions and adjust unit-tests

---

README.md

:memo: add "used in" section

---

CONTRIBUTORS.md
index.ts
package-lock.json
package.json
tsconfig.json

Provide the configuration required to publish the project as an npm package. The file `./index.ts` contains exports that will be available to the consumers of the package. As for now, I just exported all the public content from `'./src/commit'` `'./src/index'` `'./src/repository'`. The public properties of the package still need more investigation, also some changes on the modules declared in the project may be required, but I would let this as a later decision and design choice.
Fixes #208 
Please delete options that are not relevant.

feat: Make snowfs an npm package

---

.vscode/extensions.json

Adding some VS Code recommendations when opening project

:memo: add VScode recommendations

---

README.md

:memo: fix banner in readme

---

src/ignore.ts

add tmp files of Rhino to ignore

---

src/ignore.ts

Add `desktop.ini` to ignore. See #245 for more info

add desktop.ini to ignore

---

src/ignore.ts

Update default ignores

---

CONTRIBUTORS.md
README.md

Fix link url for SnowFS for Unity
Please delete options that are not relevant.

:memo: fix link url for SnowFS for Unity

---

src/commit.ts
src/odb.ts
src/reference.ts

Use strict-equals (Fixes #265)

---

src/ignore.ts

With the PR of https://github.com/snowtrack/snowfs/pull/277 and manual conflict resolution of https://github.com/snowtrack/snowfs/pull/278 I broke the main branch.

🧹 Fix ignore.ts due to broken merge

---

.github/workflows/workflow.yml
README.md
package.json

- Add caching to workflow
- Remove manual execution of `git lfs pull` and use `actions/checkout@v3` instead
- Add emojis for task labels🚀

Speedup workflow

---

.github/workflows/workflow.yml

This PR fixes the following warning:

on.pull_request must match on.branches due to CodeQL warning

---

.gitignore
main.ts
src/repository.ts

This PR fixes type errors in `main.ts`

Fix ts errors

---

LICENSE
README.md

This PR moves SnowFS to GPL v3.

Move to GPL v3
